import type { Metadata } from "next";

import "../globals.css";

import { IBM_Plex_Sans_Arabic } from "next/font/google";
import { NextIntlClientProvider, useLocale } from "next-intl";
import { getDirection } from "@/lib/types";
import { useAuth } from "@/hooks/auth";

const ibmPlex = IBM_Plex_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = useLocale();

  return (
    <html lang={locale} dir={getDirection(locale)}>
      <body className={`${ibmPlex.className}`}>
        <NextIntlClientProvider>
          <main className="w-full">
            <div className="absolute right-1/2 top-1/2 -translate-y-1/2 translate-x-1/2 w-full">
              {children}
            </div>
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
