import type { Metadata } from "next";

import "../globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

import { IBM_Plex_Sans_Arabic } from "next/font/google";
import { NextIntlClientProvider, useLocale } from "next-intl";
import { getDirection } from "@/lib/types";
import { AuthLayout } from "@/components/layout/auth-layout";
import { Navbar } from "@/components/layout/navbar/navbar";
import { BranchLayout } from "@/components/layout/branch-layout";
import { JotaiLayout } from "@/components/layout/jotai-layout";
import { DirectionProvider } from "@radix-ui/react-direction";
import { DirectionLayout } from "@/components/layout/DirectionLayout";

const ibmPlex = IBM_Plex_Sans_Arabic({
	subsets: ["arabic"],
	weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = useLocale();

	return (
		<html lang={locale} dir={getDirection(locale)}>
			<body className={`${ibmPlex.className}`}>
				<JotaiLayout>
					<AuthLayout>
						<NextIntlClientProvider>
							<DirectionLayout>
								<SidebarProvider defaultOpen={true}>
									<AppSidebar />

									<main className="flex-1 min-w-0 ">
										<Navbar />
										<BranchLayout>
											<div className="p-8 ">{children}</div>
										</BranchLayout>
									</main>
								</SidebarProvider>
							</DirectionLayout>
						</NextIntlClientProvider>
					</AuthLayout>
				</JotaiLayout>
			</body>
		</html>
	);
}
