import type { Metadata } from "next";

import "../globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

import { IBM_Plex_Sans_Arabic } from "next/font/google";
import { NextIntlClientProvider, useLocale } from "next-intl";
import { getDirection } from "@/lib/types";
import { AuthLayout } from "@/components/layout/auth-layout";
import { Navbar } from "@/components/layout/navbar/navbar";
import { BranchLayout } from "@/components/layout/branch-layout";
import { JotaiLayout } from "@/components/layout/jotai-layout";

const ibmPlex = IBM_Plex_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = useLocale();

  return (
    <html lang={locale} dir={getDirection(locale)}>
      <body className={`${ibmPlex.className}`}>
        <JotaiLayout>
          <AuthLayout>
            <NextIntlClientProvider>
              <SidebarProvider defaultOpen={true}>
                <AppSidebar />

                <main className="w-full">
                  <Navbar />
                  <BranchLayout>
                    <div className="p-8 2xl:px-[15%]">{children}</div>
                  </BranchLayout>
                </main>
              </SidebarProvider>
            </NextIntlClientProvider>
          </AuthLayout>
        </JotaiLayout>
      </body>
    </html>
  );
}
