import z from "zod";

export const measurementSchema = z.object({
  general: z.object({
    thobeLength: z.coerce.number().nonnegative().optional(),
    thobeBackLength: z.coerce.number().nonnegative().optional(),
    shoulderWidth: z.coerce.number().nonnegative().optional(),
    shoulderRotation: z.coerce.number().nonnegative().optional(),
    sleeveLength: z.coerce.number().nonnegative().optional(),
    upperSleeveWidth: z.coerce.number().nonnegative().optional(),
    middleSleeveWidth: z.coerce.number().nonnegative().optional(),
    wristWidth: z.coerce.number().nonnegative().optional(),
    chestFront: z.coerce.number().nonnegative().optional(),
    chestBack: z.coerce.number().nonnegative().optional(),
    chestFull: z.coerce.number().nonnegative().optional(),
    bottomWidth: z.coerce.number().nonnegative().optional(),
    cuffBottomWidth: z.coerce.number().nonnegative().optional(),
    addedInfo: z.coerce.number().nonnegative().optional(),
    sidePocket: z.coerce.number().nonnegative().optional(),
    waistWidth: z.coerce.number().nonnegative().optional(),
    hipWidth: z.coerce.number().nonnegative().optional(),
  }),
  neck: z.object({
    neckLength: z.coerce.number().nonnegative().optional(),
    neckBackLength: z.coerce.number().nonnegative().optional(),
    neckWidth: z.coerce.number().nonnegative().optional(),
    neckButtonCount: z.coerce.number().nonnegative().optional(),
    neckDesign: z.enum(["plain", "v-neck", "french", "chinese", "royal"]),
    neckShape: z.enum(["square", "rounded"]),
    neckFill: z.enum(["1", "2"]),
    neckButtonType: z.enum(["normal", "opposite"]),
    neckButtonholeType: z.enum(["normal", "arawi"]),
    neckButtonMaterial: z.enum(["plastic", "steel"]),
    neckButtonVisibility: z.enum(["visible", "invisibile"]),
  }),
  wrist: z.object({
    cuffType: z.enum(["normal", "cufflinks"]),
    cuffLength: z.coerce.number().nonnegative().optional(),
    cuffWidth: z.coerce.number().nonnegative().optional(),
    wristDesign: z.enum([
      "plain",
      "on",
      "minced",
      "rounded",
      "square",
      "french",
      "double",
    ]),
    wristButtonNumber: z.coerce.number().nonnegative().optional(),
    wristMaterialLayers: z.enum(["1", "2"]),
    sleeveCrumbNumber: z.enum(["0", "1", "2"]),
  }),

  chestPocket: z.object({
    chestPocketLength: z.coerce.number().nonnegative().optional(),
    chestPocketWidth: z.coerce.number().nonnegative().optional(),
    betweenChestPocketShoulder: z.coerce.number().nonnegative().optional(),
    chestPocketPenType: z.enum(["no", "halfLength", "fullLength"]),
    chestPocketDesign: z.enum(["official", "kuwaiti", "model"]),
    chestPocketShape: z.enum(["rounded", "square"]),
    chestPocketVisibility: z.enum(["visible", "invisible"]),
  }),

  sidePockets: z.object({
    phonePocketLength: z.coerce.number().nonnegative().optional(),
    phonePocketWidth: z.coerce.number().nonnegative().optional(),
    walletPocketLength: z.coerce.number().nonnegative().optional(),
    walletPocketWidth: z.coerce.number().nonnegative().optional(),
  }),
  jabzoor: z.object({
    jabzoorHoleType: z.enum(["push", "buttons", "zip"]),
    jabzoorLength: z.coerce.number().nonnegative().optional(),
    jabzoorWidth: z.coerce.number().nonnegative().optional(),
    jabzoorDesign: z.enum([
      "normal",
      "combination",
      "supportedStitch",
      "fill",
      "fullPush",
    ]),
    jabzoorVisibility: z.enum(["visible", "invisible"]),
    jabzoorShape: z.enum(["square", "rounded", "minced"]),
    jabzoorPushMaterial: z.enum(["plastic", "steel"]),
  }),
});
