import type { Metadata } from "next";

import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

import { IBM_Plex_Sans_Arabic } from "next/font/google";
import { Navbar } from "@/components/ui/navbar";



const ibmPlex = IBM_Plex_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${ibmPlex.className}`}>
        <SidebarProvider
          defaultOpen={true}
          style={{
            "--sidebar-width-icon": "4rem",
            "--sidebar-width-mobile": "20rem",
          }}
        >
          <AppSidebar />

          <main className="w-full">
            <Navbar />
            <div className="p-8">{children}</div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
